server:
  port: 84
spring:
  application:
    name: cloudalibaba-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel Dashboard的地址
        port: 8719  #默认8719端口，假如被占用会从8719依次开始扫描，直至找到未被占用的端口
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: '*'
service-url:
  nacos-user-service: http://cloudalibaba-nacos-provider-payment
feign:  #激活feign对Sentinel的支持
  sentinel:
    enabled: true