server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      seata:
        tx-service-group: fsp_tx_group  #fsp_tx_group自定义配置中seata-server中配置一样
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    # mysql驱动类
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_order?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: pass
feign:
  hystrix:
    enabled: false
#  client:
#    config:
#      default:
#        connect-timeout: 300000
#        read-timeout: 300000

mybatis:
  mapperLocations: classpath*:mapper/*.xml