server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: payment_routh #payment_routh   路由的id没有固定规则但要求唯一，建议配合服务名
          #: http://localhost:8001/ #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/get/**      #断言路径相匹配的进行路由

        - id: payment_routh2  #payment_routh   路由的id没有固定规则但要求唯一，建议配合服务名
          #: http://localhost:8001/ #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/** #断言路径相匹配的进行路由
            #- After=2020-07-07T13:34:03.879+08:00[Asia/Shanghai]
            #- Cookie=username,llp
            #- Header=X-Requset-Id,\d+ #请求头要用X-Request-Id属性并且值为整数的正则表达式
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/